/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Registration = IDL.Record({
  'id' : IDL.Nat,
  'teamName' : IDL.Text,
  'captainName' : IDL.Text,
  'playerCount' : IDL.Text,
  'timestamp' : IDL.Int,
  'villageName' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'registerTeam' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Registration = IDL.Record({
    'id' : IDL.Nat,
    'teamName' : IDL.Text,
    'captainName' : IDL.Text,
    'playerCount' : IDL.Text,
    'timestamp' : IDL.Int,
    'villageName' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'registerTeam' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };